name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: go test -cover -v ./...

      - name: Redis End-to-End Test
        run: go test -v ./redis -redis redis://localhost/0/abcd

      - name: Full End-to-End Tests
        run: REDIS=redis://localhost/1 ./test_helpers/end2end.sh

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
